apiVersion: v1
kind: Service
metadata:
  name: user-service-prod
spec:
  selector:
    app: user-app-dev
  ports:
    - protocol: TCP
      port: 803
      targetPort: 803
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-app-prod
  template:
    metadata:
      labels:
        app: user-app-prod
    spec:
      containers:
      - name: user-app-prod
        image: iitcloud.azurecr.io/user-app:latest  # Replace with your Docker Hub username
        ports:
        - containerPort: 803
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-prod
spec:
  selector:
    app: user-app-prod
  ports:
    - protocol: TCP
      port: 803
      targetPort: 802
  type: LoadBalancer
