apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-app
  template:
    metadata:
      labels:
        app: database-app
    spec:
      containers:
      - name: database-app
        image: chanakaj/database-app:latest  # Replace with your Docker Hub username
        ports:
        - containerPort: 8001
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
