apiVersion: apps/v1
kind: Deployment
metadata:
  name: gui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gui-app
  template:
    metadata:
      labels:
        app: gui-app
    spec:
      containers:
      - name: gui-app
        image: chanakaj/gui-app:latest  # Replace with your Docker Hub username
        ports:
        - containerPort: 8002
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
